# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Automated tests

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'
  workflow_call:



env:
  MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"
  DOCKER_TARGET: federator-certificate-manager
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Full history is recommended for accurate Sonar analysis and PR decoration
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-password: 'GH_PACKAGES_PAT'
      - name: Build and Test
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
        run: ./mvnw $MAVEN_CLI_OPTS verify
      - name: Verify JaCoCo XML exists
        run: ls -l target/site/jacoco/jacoco.xml
      - name: SonarQube Scan
        if: github.actor != 'dependabot[bot]'
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_N3 }}
        run: ./mvnw $MAVEN_CLI_OPTS org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=National-Node-Net_federator-certificate-manager -Dsonar.organization=national-node-net -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  lint:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-password: 'GH_PACKAGES_PAT'
      - name: Lint
        env:
          GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
        run: ./mvnw $MAVEN_CLI_OPTS spotless:check
  security-scanning:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-password: 'GH_PACKAGES_PAT'
    
      - name: Get version
        id: get_version
        run: echo project_version=$(./mvnw $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Login to ghcr.io
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Get server jar
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: federator-certificate-manager-*.jar
          path: target
          merge-multiple: true

      - name: Build Server Image
        run: docker build --no-cache --build-arg JAR_NAME="federator-certificate-manager-${{ steps.get_version.outputs.project_version}}" -t ghcr.io/${REPO}/federator-certificate-manager:staged -f "${{ github.workspace }}/docker/Dockerfile" --target ${{ env.DOCKER_TARGET }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ghcr.io/${{ env.REPO }}/federator-certificate-manager:staged
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          trivyignores: .trivyignore
        continue-on-error: false

      - name: Clean up docker image
        run: docker rmi ghcr.io/${REPO}/federator-certificate-manager:staged
